project:
  type: website

website:
  title: "Welcome to my blog"
  site-url: "https://www.pmassicotte.com"
  description: "Numerical ecologist | Data visualization | R enthousiast"
  sharing: [twitter]
  navbar:
    right:
      - about.qmd
      - publications.qmd
      - presentations.qmd
      - workshops.qmd
      - icon: github
        href: https://github.com/pmassicotte
      - icon: twitter
        href: https://twitter.com/philmassicotte
      - icon: stack-overflow
        href: "users/5558188/philippe-massicotte"
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css
    code-link: true
    highlight-style: ally
    mainfont: Montserrat

comments:
  utterances:
    repo: pmassicotte/r-blog

execute:
  freeze: auto