project:
  type: website

website:
  page-navigation: true
  title: "Philippe Massicotte"
  site-url: "https://www.pmassicotte.com"
  description: "Numerical ecologist | Data visualization | R enthousiast"
  google-analytics: UA-142521801-1
  cookie-consent: false
  twitter-card: true
  open-graph:
    site-name: "Just another R blog (Philippe Massicotte)"
  navbar:
    right: 
      - publications.qmd
      - presentations.qmd
      - workshops.qmd
      - about.qmd
      - icon: github
        href: https://github.com/pmassicotte
      - icon: twitter
        href: https://twitter.com/philmassicotte
      - icon: mastodon
        href: https://fosstodon.org/@philmassicotte
      - icon: stack-overflow
        href: "users/5558188/philippe-massicotte"
      - icon: rss
        href: index.xml
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    code-link: true
    highlight-style: arrow
    mainfont: Montserrat
    fig-dpi: 600
    fig-align: center
    fig-width: 8
    fig-asp: 0.618 # 1 / pi
    fig-format: png
    

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

comments:
  utterances:
    repo: pmassicotte/PMassicotte.github.io

execute:
  freeze: auto
  message: false
  warning: false
  echo: true
