project:
  type: website

website:
  page-navigation: true
  title: "Philippe Massicotte"
  site-url: "https://www.pmassicotte.com"
  description: "Numerical ecologist | Data visualization | R enthousiast"
  google-analytics: UA-142521801-1
  cookie-consent: false
  twitter-card: true
  navbar:
    right: 
      - publications.qmd
      - presentations.qmd
      - workshops.qmd
      - about.qmd
      - icon: github
        href: https://github.com/pmassicotte
      - icon: twitter
        href: https://twitter.com/philmassicotte
      - icon: stack-overflow
        href: "users/5558188/philippe-massicotte"
      - icon: rss
        href: index.xml
format:
  html:
    theme: flatly
    css: styles.css
    code-link: true
    highlight-style: ally
    mainfont: Montserrat

comments:
  utterances:
    repo: pmassicotte/PMassicotte.github.io

execute:
  freeze: auto