---
title: 'Publications'
comments: false
execute:
  freeze: false
---

```{r lockfile, include=FALSE}
options(
  repos = c(
    CRAN = "https://packagemanager.posit.co/cran/__linux__/jammy/latest"
  )
)

renv::use(
  askpass     = "askpass@1.2.0",
  base64enc   = "base64enc@0.1-3",
  bslib       = "bslib@0.7.0",
  cachem      = "cachem@1.0.8",
  cli         = "cli@3.6.2",
  curl        = "curl@5.2.1",
  digest      = "digest@0.6.35",
  dplyr       = "dplyr@1.1.4",
  evaluate    = "evaluate@0.23",
  fansi       = "fansi@1.0.6",
  fastmap     = "fastmap@1.1.1",
  fontawesome = "fontawesome@0.5.2",
  fs          = "fs@1.6.4",
  generics    = "generics@0.1.3",
  glue        = "glue@1.7.0",
  gt          = "gt@0.10.1",
  highr       = "highr@0.10",
  htmltools   = "htmltools@0.5.8.1",
  httr2       = "httr2@1.0.1",
  jquerylib   = "jquerylib@0.1.4",
  jsonlite    = "jsonlite@1.8.8",
  knitr       = "knitr@1.46",
  lifecycle   = "lifecycle@1.0.4",
  magrittr    = "magrittr@2.0.3",
  memoise     = "memoise@2.0.1",
  mime        = "mime@0.12",
  openssl     = "openssl@2.1.2",
  pillar      = "pillar@1.9.0",
  pkgconfig   = "pkgconfig@2.0.3",
  purrr       = "purrr@1.0.2",
  R6          = "R6@2.5.1",
  rappdirs    = "rappdirs@0.3.3",
  renv        = "renv@1.0.7",
  rlang       = "rlang@1.1.3",
  rmarkdown   = "rmarkdown@2.26",
  sass        = "sass@0.4.9",
  stringi     = "stringi@1.8.3",
  stringr     = "stringr@1.5.1",
  sys         = "sys@3.4.2",
  tibble      = "tibble@3.2.1",
  tidyselect  = "tidyselect@1.2.1",
  tinytex     = "tinytex@0.50",
  utf8        = "utf8@1.2.4",
  vctrs       = "vctrs@0.6.5",
  withr       = "withr@3.0.0",
  xfun        = "xfun@0.43",
  yaml        = "yaml@2.3.8"
)
```

::: {.callout-note}
This is the list of my academic publications. I try as much as possible to publish in open access journals. However, if you can not find the associated PDF, please contact me. I will glady send it to you!
:::

```{r}
#| echo: false
#| warning: false
#| message: false
#| eval: true

library(dplyr)
library(httr2)
library(gt)
library(glue)
library(purrr)
library(stringr)

key <- Sys.getenv("ZOTERO_KEY")

res <- request("https://api.zotero.org/users/5837870/publications/items/") |>
  req_headers(
    "Zotero-API-Version" = "3",
    "Zotero-API-Key" = key,
    "Accept" = "application/json"
  ) |>
  req_url_query(limit = 100, sort = "date", direction = "desc") |>
  req_perform() |>
  resp_body_json(simplifyVector = TRUE) |>
  as_tibble()

dat <- res$data |>
  as_tibble() |>
  mutate(authors = map_chr(creators, ~ toString(paste(.$firstName, .$lastName)))) |>
  filter(authors != "") |>
  mutate(year = str_match(date, "\\d{4}")) |>
  mutate(across(where(is.character), \(x) ifelse(is.na(x), "", x))) |>
  mutate(DOI = case_when(
    DOI == "" ~ "",
    TRUE ~ glue("<a href = https://doi.org/{DOI}>View article</a>")
  )) |>
  mutate(row = glue("<p style='color:#2C3E50; font-size:1em; font-style: italic; font-weight: bold; font-family: Poppins'>{title}</p><p style='color:#616D7E; font-size:0.85em; font-family: Poppins'>{authors}, <em>{publicationTitle}</em> ({year}) {DOI}</p>")) |>
  select(row)

dat |>
  gt() |>
  fmt_markdown(everything()) |>
  cols_align(align = "left") |>
  tab_options(
    data_row.padding = px(20),
    column_labels.hidden = TRUE
  ) |>
  tab_style(
    style = cell_borders(
      sides = c("top", "bottom"),
      color = "#2C3E50",
      weight = px(2),
      style = "solid"
    ),
    locations = cells_body(
      columns = everything(),
      rows = everything()
    )
  ) |>
  opt_table_outline(style = "none")
```
